title: "Francisco Juan"
slogan: "Software engineer"
url: "http://www.fjuan.es"
author: "Francisco Juan"
author_email: "francisco.juan@gmail.com"
keywords: "Francisco Juan, fjuan, curriculum, resume, cv, software engineer, ruby, ruby on rails, ember, elasticsearch, wordpress, recetas de mama"

permalink: "pretty"
lsi: "false"
exclude:
  - private
