title: "Francisco de Juan"
slogan: "Ruby developer"
url: "http://www.redtux.io"
author: "Francisco de Juan"
author_email: "francisco.juan@redtux.io"
keywords: "Francisco de Juan, fjuan, curriculum, resume, cv, ruby, ruby developer, ruby on rails, wordpress, recetas de mama"

permalink: "pretty"
lsi: "false"
exclude:
  - private
