title: Francisco de Juan
slogan: "Creating webs with ruby & writting cooking books"
url: http://www.fjuan.es
author: Francisco de Juan
author_email: me@fjuan.es

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
exclude: private
