title: fjuan's blog
slogan: Welcome to my blog
url: http://www.fjuan.es
feed-url: http://feeds.feedburner.com/fjuan
author: Francisco de Juan
author_email: contacto@fjuan.es

permalink: pretty
auto: true
server: true
lsi: false
pygments: true
exclude: private

paginate: 3

navigation:
  - name: Blog
    url: /
    layout: post
  - name: Libros
    url: /books/
    layout: book
  - name: "Sobre mi"
    url: /about/

