title: "Francisco Juan"
slogan: "Ruby developer"
url: "http://www.fjuan.es"
author: "Francisco Juan"
author_email: "francisco.juan@gmail.com"
keywords: "Francisco Juan, fjuan, curriculum, resume, cv, ruby, ruby developer, ruby on rails, wordpress, recetas de mama"

permalink: "pretty"
lsi: "false"
exclude:
  - private
