title: Francisco de Juan
slogan: "Creating webs with ruby & writing cooking books"
url: http://www.fjuan.es
author: Francisco de Juan
author_email: me@fjuan.es
keywords: "Francisco de Juan, fjuan, curriculum, resume, cv, splendeo, recetas de mama, ruby, ruby on rails, wordpress"

permalink: pretty
lsi: false
highlighter: true
exclude: 
  - private
